import { StyleSheet } from 'react-native'
import { theme } from '../theme'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  scrollContent: {
    padding: theme.spacing.lg,
    paddingBottom: 100,
  },
  searchCard: {
    marginBottom: theme.spacing.md,
  },
  searchCardCollapsed: {
    marginBottom: theme.spacing.md,
  },
  collapsedSearchContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  collapsedSearchText: {
    color: theme.colors.text,
    fontSize: 13,
    fontFamily: theme.fontFamily.semibold,
    flex: 1,
  },
  collapsedSearchAction: {
    color: theme.colors.primary,
    fontSize: 12,
    fontFamily: theme.fontFamily.bold,
    textTransform: 'uppercase',
  },
  cardTitle: {
    color: theme.colors.textMuted,
    fontSize: 12,
    fontFamily: theme.fontFamily.bold,
    marginBottom: 8,
  },
  searchRow: {
    flexDirection: 'row',
    gap: 8,
  },
  input: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: theme.radius.lg,
    color: theme.colors.text,
    fontFamily: theme.fontFamily.regular,
    paddingHorizontal: theme.spacing.md,
    height: 44,
  },
  inputFocused: {
    borderColor: theme.colors.primary,
    borderWidth: 1.5,
    backgroundColor: 'rgba(0, 161, 224, 0.08)',
  },
  scanBtn: {
    width: 44,
    height: 44,
    borderRadius: theme.radius.lg,
    backgroundColor: 'rgba(0, 161, 224, 0.15)',
    borderWidth: 1,
    borderColor: theme.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchBtn: {
    width: 44,
    height: 44,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  importBtn: {
    flexDirection: 'row',
    backgroundColor: theme.colors.surfaceLight,
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: theme.radius.lg,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    marginBottom: theme.spacing.xl,
  },
  importBtnText: {
    color: '#fff',
    fontFamily: theme.fontFamily.bold,
  },
  loadingContainer: {
    paddingVertical: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoTextContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: theme.spacing.xl,
  },
  logoTextMain: {
    color: '#ffffff',
    fontSize: 26,
    fontFamily: theme.fontFamily.bold,
  },
  logoTextSuffix: {
    color: theme.colors.primary,
    fontSize: 26,
    fontFamily: theme.fontFamily.regular,
    letterSpacing: 1,
  },
  loadingSpinner: {
    marginBottom: theme.spacing.md,
  },
  loadingText: {
    color: theme.colors.textMuted,
    fontSize: 13,
  },
  resultsContainer: {
    marginTop: theme.spacing.sm,
  },
  panelHeader: {
    marginBottom: theme.spacing.md,
  },
  panelTitle: {
    color: theme.colors.text,
    fontSize: 18,
    fontFamily: theme.fontFamily.bold,
  },
  panelMeta: {
    color: theme.colors.textMuted,
    fontSize: 12,
    marginTop: 2,
  },
  panelHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: theme.spacing.md,
  },
  ewsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.primary,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: theme.radius.md,
    gap: 6,
  },
  ewsButtonText: {
    color: '#fff',
    fontSize: 11,
    fontFamily: theme.fontFamily.bold,
  },
  kpiScroll: {
    paddingBottom: theme.spacing.md,
    gap: 10,
  },
  sectionLabel: {
    color: theme.colors.textDim,
    fontSize: 10,
    fontFamily: theme.fontFamily.bold,
    letterSpacing: 1.5,
    marginTop: theme.spacing.lg,
    marginBottom: theme.spacing.md,
  },
  iaCard: {
    marginBottom: theme.spacing.lg,
  },
  iaHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  iaDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: theme.colors.primary,
  },
  iaTitle: {
    color: theme.colors.text,
    fontSize: 13,
    fontFamily: theme.fontFamily.bold,
    flex: 1,
  },
  iaButtonPressable: {
    borderRadius: theme.radius.md,
    overflow: 'hidden',
  },
  iaButton: {
    paddingVertical: 12,
    alignItems: 'center',
  },
  iaButtonText: {
    color: '#fff',
    fontFamily: theme.fontFamily.bold,
    fontSize: 13,
  },
  emptyText: {
    color: theme.colors.textDim,
    fontSize: 13,
    fontStyle: 'italic',
    textAlign: 'center',
    paddingVertical: 12,
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
    borderRadius: theme.radius.md,
    padding: 3,
    marginBottom: theme.spacing.md,
  },
  tab: {
    flex: 1,
    paddingVertical: 8,
    minHeight: 44,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: theme.radius.sm,
  },
  tabActive: {
    backgroundColor: theme.colors.surfaceLight,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  tabText: {
    fontSize: 12,
    fontFamily: theme.fontFamily.medium,
    color: theme.colors.textMuted,
  },
  tabTextActive: {
    color: theme.colors.primary,
    fontFamily: theme.fontFamily.bold,
  },
  pickerButton: {
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: theme.radius.lg,
    paddingHorizontal: theme.spacing.md,
    height: 44,
    justifyContent: 'center',
  },
  pickerButtonDisabled: {
    opacity: 0.4,
  },
  pickerButtonText: {
    color: theme.colors.textDim,
    fontSize: 13,
    fontFamily: theme.fontFamily.regular,
  },
  pickerButtonTextActive: {
    color: theme.colors.text,
    fontSize: 13,
    fontFamily: theme.fontFamily.semibold,
  },
  detailedFiltersCard: {
    marginBottom: theme.spacing.md,
    padding: theme.spacing.sm,
  },
  detailedSearchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  searchFieldWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: theme.radius.md,
    paddingHorizontal: 10,
    height: 44,
  },
  searchFieldIcon: {
    marginRight: 6,
  },
  detailedSearchInput: {
    flex: 1,
    color: theme.colors.text,
    fontFamily: theme.fontFamily.regular,
    fontSize: 13,
    height: '100%',
    padding: 0,
  },
  clearBtn: {
    padding: 4,
  },
  dateFilterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceLight,
    borderColor: theme.colors.border,
    borderWidth: 1,
    borderRadius: theme.radius.md,
    paddingHorizontal: 10,
    height: 44,
    gap: 6,
    maxWidth: 150,
  },
  dateFilterBtnText: {
    color: theme.colors.text,
    fontSize: 12,
    fontFamily: theme.fontFamily.semibold,
  },
  kpiSubtext: {
    color: theme.colors.textMuted,
    fontSize: 9,
    fontFamily: theme.fontFamily.regular,
    marginBottom: 2,
  },
  kpiTimestamp: {
    color: theme.colors.textDim,
    fontSize: 9,
    fontFamily: theme.fontFamily.regular,
  },
  kpiInterval: {
    color: theme.colors.textDim,
    fontSize: 8.5,
    fontFamily: theme.fontFamily.regular,
    marginTop: 1,
  },
  initialHeaderContainer: {
    alignItems: 'center',
    marginBottom: theme.spacing.xl,
    paddingHorizontal: theme.spacing.md,
  },
  initialLogoRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  initialHeaderMain: {
    fontFamily: theme.fontFamily.bold,
    fontSize: 28,
    color: '#ffffff',
  },
  initialHeaderSuffix: {
    fontFamily: theme.fontFamily.medium,
    fontSize: 28,
    color: theme.colors.primary,
    letterSpacing: 0.5,
  },
  initialSubtitle: {
    color: theme.colors.textMuted,
    fontSize: 13,
    fontFamily: theme.fontFamily.medium,
    textAlign: 'center',
    lineHeight: 18,
    marginTop: 6,
    opacity: 0.8,
  },
  resultsHeaderBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: theme.spacing.sm,
    marginBottom: theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  backBtn: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  resultsHeaderTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  resultsLogoMain: {
    fontFamily: theme.fontFamily.bold,
    fontSize: 16,
    color: '#ffffff',
  },
  resultsLogoSuffix: {
    fontFamily: theme.fontFamily.medium,
    fontSize: 16,
    color: theme.colors.primary,
  },
})
